// Code generated by YGOT. DO NOTEDIT.
/*
Package api is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /go/pkg/mod/github.com/openconfig/ygot@v0.24.1/genutil/names.go
using the following YANG input files:
	- /config-model/yang/intel-sra-source@2022-09-24.yang
	- /config-model/yang/intel-sra@2022-09-24.yang
Imported modules were sourced from:
	- "/config-model/yang"/...
*/
package api

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
	ΛEnumTypes map[string][]reflect.Type
)

func init() {
	var err error
	initΛEnumTypes()
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	RetailArea	map[string]*IntelSraSource_RetailArea	`path:"retail-area" module:"intel-sra-source"`
	ShelfMonitoring	*IntelSra_ShelfMonitoring	`path:"shelf-monitoring" module:"intel-sra"`
	ShopperMonitoring	*IntelSra_ShopperMonitoring	`path:"shopper-monitoring" module:"intel-sra"`
	StoreTrafficMonitoring	*IntelSra_StoreTrafficMonitoring	`path:"store-traffic-monitoring" module:"intel-sra"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// NewRetailArea creates a new entry in the RetailArea list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewRetailArea(AreaId string) (*IntelSraSource_RetailArea, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.RetailArea == nil {
		t.RetailArea = make(map[string]*IntelSraSource_RetailArea)
	}

	key := AreaId

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.RetailArea[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list RetailArea", key)
	}

	t.RetailArea[key] = &IntelSraSource_RetailArea{
		AreaId: &AreaId,
	}

	return t.RetailArea[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Device.
func (*Device) ΛBelongingModule() string {
	return ""
}


// IntelSraSource_RetailArea represents the /intel-sra-source/retail-area YANG schema element.
type IntelSraSource_RetailArea struct {
	AreaId	*string	`path:"area-id" module:"intel-sra-source"`
	Description	*string	`path:"description" module:"intel-sra-source"`
	DisplayName	*string	`path:"display-name" module:"intel-sra-source"`
	Image	*string	`path:"image" module:"intel-sra-source"`
	Location	*IntelSraSource_RetailArea_Location	`path:"location" module:"intel-sra-source"`
	Source	map[string]*IntelSraSource_RetailArea_Source	`path:"source" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea) IsYANGGoStruct() {}

// NewSource creates a new entry in the Source list of the
// IntelSraSource_RetailArea struct. The keys of the list are populated from the input
// arguments.
func (t *IntelSraSource_RetailArea) NewSource(SourceId string) (*IntelSraSource_RetailArea_Source, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Source == nil {
		t.Source = make(map[string]*IntelSraSource_RetailArea_Source)
	}

	key := SourceId

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Source[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Source", key)
	}

	t.Source[key] = &IntelSraSource_RetailArea_Source{
		SourceId: &SourceId,
	}

	return t.Source[key], nil
}

// ΛListKeyMap returns the keys of the IntelSraSource_RetailArea struct, which is a YANG list entry.
func (t *IntelSraSource_RetailArea) ΛListKeyMap() (map[string]interface{}, error) {
	if t.AreaId == nil {
		return nil, fmt.Errorf("nil value for key AreaId")
	}

	return map[string]interface{}{
		"area-id": *t.AreaId,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea.
func (*IntelSraSource_RetailArea) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSraSource_RetailArea_Location represents the /intel-sra-source/retail-area/location YANG schema element.
type IntelSraSource_RetailArea_Location struct {
	CoordinateSystem	E_IntelSraSource_RetailArea_Location_CoordinateSystem	`path:"coordinate-system" module:"intel-sra-source"`
	OrientationX	*int64	`path:"orientation-x" module:"intel-sra-source"`
	X	*int64	`path:"x" module:"intel-sra-source"`
	Y	*int64	`path:"y" module:"intel-sra-source"`
	Z	*int64	`path:"z" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea_Location implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea_Location) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Location) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea_Location"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Location) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea_Location) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea_Location.
func (*IntelSraSource_RetailArea_Location) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSraSource_RetailArea_Source represents the /intel-sra-source/retail-area/source YANG schema element.
type IntelSraSource_RetailArea_Source struct {
	Description	*string	`path:"description" module:"intel-sra-source"`
	DisplayName	*string	`path:"display-name" module:"intel-sra-source"`
	Image	*string	`path:"image" module:"intel-sra-source"`
	Location	*IntelSraSource_RetailArea_Source_Location	`path:"location" module:"intel-sra-source"`
	SourceId	*string	`path:"source-id" module:"intel-sra-source"`
	State	*IntelSraSource_RetailArea_Source_State	`path:"state" module:"intel-sra-source"`
	Video	*IntelSraSource_RetailArea_Source_Video	`path:"video" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea_Source implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea_Source) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the IntelSraSource_RetailArea_Source struct, which is a YANG list entry.
func (t *IntelSraSource_RetailArea_Source) ΛListKeyMap() (map[string]interface{}, error) {
	if t.SourceId == nil {
		return nil, fmt.Errorf("nil value for key SourceId")
	}

	return map[string]interface{}{
		"source-id": *t.SourceId,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea_Source"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea_Source) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea_Source.
func (*IntelSraSource_RetailArea_Source) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSraSource_RetailArea_Source_Location represents the /intel-sra-source/retail-area/source/location YANG schema element.
type IntelSraSource_RetailArea_Source_Location struct {
	CoordinateSystem	E_IntelSraSource_RetailArea_Location_CoordinateSystem	`path:"coordinate-system" module:"intel-sra-source"`
	OrientationX	*int64	`path:"orientation-x" module:"intel-sra-source"`
	X	*int64	`path:"x" module:"intel-sra-source"`
	Y	*int64	`path:"y" module:"intel-sra-source"`
	Z	*int64	`path:"z" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea_Source_Location implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea_Source_Location) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_Location) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea_Source_Location"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_Location) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea_Source_Location) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea_Source_Location.
func (*IntelSraSource_RetailArea_Source_Location) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSraSource_RetailArea_Source_State represents the /intel-sra-source/retail-area/source/state YANG schema element.
type IntelSraSource_RetailArea_Source_State struct {
	Error	*string	`path:"error" module:"intel-sra-source"`
	ErrorSince	*string	`path:"error-since" module:"intel-sra-source"`
	Status	*string	`path:"status" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea_Source_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea_Source_State) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_State) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea_Source_State"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_State) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea_Source_State) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea_Source_State.
func (*IntelSraSource_RetailArea_Source_State) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSraSource_RetailArea_Source_Video represents the /intel-sra-source/retail-area/source/video YANG schema element.
type IntelSraSource_RetailArea_Source_Video struct {
	Path	*string	`path:"path" module:"intel-sra-source"`
	SourceType	E_IntelSraSource_RetailArea_Source_Video_SourceType	`path:"source-type" module:"intel-sra-source"`
}

// IsYANGGoStruct ensures that IntelSraSource_RetailArea_Source_Video implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSraSource_RetailArea_Source_Video) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_Video) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSraSource_RetailArea_Source_Video"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSraSource_RetailArea_Source_Video) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSraSource_RetailArea_Source_Video) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSraSource_RetailArea_Source_Video.
func (*IntelSraSource_RetailArea_Source_Video) ΛBelongingModule() string {
	return "intel-sra-source"
}


// IntelSra_ShelfMonitoring represents the /intel-sra/shelf-monitoring YANG schema element.
type IntelSra_ShelfMonitoring struct {
	Default	*string	`path:"default" module:"intel-sra"`
	Enable	*bool	`path:"enable" module:"intel-sra"`
	ObjectDetectionApplication	*IntelSra_ShelfMonitoring_ObjectDetectionApplication	`path:"object-detection-application" module:"intel-sra"`
	RetailArea	map[string]*IntelSra_ShelfMonitoring_RetailArea	`path:"retail-area" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShelfMonitoring implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShelfMonitoring) IsYANGGoStruct() {}

// NewRetailArea creates a new entry in the RetailArea list of the
// IntelSra_ShelfMonitoring struct. The keys of the list are populated from the input
// arguments.
func (t *IntelSra_ShelfMonitoring) NewRetailArea(AreaRef string) (*IntelSra_ShelfMonitoring_RetailArea, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.RetailArea == nil {
		t.RetailArea = make(map[string]*IntelSra_ShelfMonitoring_RetailArea)
	}

	key := AreaRef

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.RetailArea[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list RetailArea", key)
	}

	t.RetailArea[key] = &IntelSra_ShelfMonitoring_RetailArea{
		AreaRef: &AreaRef,
	}

	return t.RetailArea[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShelfMonitoring"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShelfMonitoring) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShelfMonitoring.
func (*IntelSra_ShelfMonitoring) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShelfMonitoring_ObjectDetectionApplication represents the /intel-sra/shelf-monitoring/object-detection-application YANG schema element.
type IntelSra_ShelfMonitoring_ObjectDetectionApplication struct {
	Device	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device	`path:"device" module:"intel-sra"`
	Model	*string	`path:"model" module:"intel-sra"`
	ModelState	*IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState	`path:"model-state" module:"intel-sra"`
	Precision	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision	`path:"precision" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShelfMonitoring_ObjectDetectionApplication) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShelfMonitoring_ObjectDetectionApplication"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShelfMonitoring_ObjectDetectionApplication.
func (*IntelSra_ShelfMonitoring_ObjectDetectionApplication) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState represents the /intel-sra/shelf-monitoring/object-detection-application/model-state YANG schema element.
type IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState struct {
	ActiveModelFile	*string	`path:"active-model-file" module:"intel-sra"`
	ActiveModelName	*string	`path:"active-model-name" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState.
func (*IntelSra_ShelfMonitoring_ObjectDetectionApplication_ModelState) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShelfMonitoring_RetailArea represents the /intel-sra/shelf-monitoring/retail-area YANG schema element.
type IntelSra_ShelfMonitoring_RetailArea struct {
	AreaRef	*string	`path:"area-ref" module:"intel-sra"`
	Enabled	*bool	`path:"enabled" module:"intel-sra"`
	StreamCount	*uint8	`path:"stream-count" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShelfMonitoring_RetailArea implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShelfMonitoring_RetailArea) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the IntelSra_ShelfMonitoring_RetailArea struct, which is a YANG list entry.
func (t *IntelSra_ShelfMonitoring_RetailArea) ΛListKeyMap() (map[string]interface{}, error) {
	if t.AreaRef == nil {
		return nil, fmt.Errorf("nil value for key AreaRef")
	}

	return map[string]interface{}{
		"area-ref": *t.AreaRef,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_RetailArea) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShelfMonitoring_RetailArea"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShelfMonitoring_RetailArea) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShelfMonitoring_RetailArea) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShelfMonitoring_RetailArea.
func (*IntelSra_ShelfMonitoring_RetailArea) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring represents the /intel-sra/shopper-monitoring YANG schema element.
type IntelSra_ShopperMonitoring struct {
	Default	*string	`path:"default" module:"intel-sra"`
	EmotionRecognitionApplication	*IntelSra_ShopperMonitoring_EmotionRecognitionApplication	`path:"emotion-recognition-application" module:"intel-sra"`
	Enable	*bool	`path:"enable" module:"intel-sra"`
	FaceDetectionApplication	*IntelSra_ShopperMonitoring_FaceDetectionApplication	`path:"face-detection-application" module:"intel-sra"`
	HeadPoseDetectionApplication	*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication	`path:"head-pose-detection-application" module:"intel-sra"`
	RetailArea	map[string]*IntelSra_ShopperMonitoring_RetailArea	`path:"retail-area" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring) IsYANGGoStruct() {}

// NewRetailArea creates a new entry in the RetailArea list of the
// IntelSra_ShopperMonitoring struct. The keys of the list are populated from the input
// arguments.
func (t *IntelSra_ShopperMonitoring) NewRetailArea(AreaRef string) (*IntelSra_ShopperMonitoring_RetailArea, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.RetailArea == nil {
		t.RetailArea = make(map[string]*IntelSra_ShopperMonitoring_RetailArea)
	}

	key := AreaRef

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.RetailArea[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list RetailArea", key)
	}

	t.RetailArea[key] = &IntelSra_ShopperMonitoring_RetailArea{
		AreaRef: &AreaRef,
	}

	return t.RetailArea[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring.
func (*IntelSra_ShopperMonitoring) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_EmotionRecognitionApplication represents the /intel-sra/shopper-monitoring/emotion-recognition-application YANG schema element.
type IntelSra_ShopperMonitoring_EmotionRecognitionApplication struct {
	Device	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device	`path:"device" module:"intel-sra"`
	Model	*string	`path:"model" module:"intel-sra"`
	ModelState	*IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState	`path:"model-state" module:"intel-sra"`
	Precision	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision	`path:"precision" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_EmotionRecognitionApplication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_EmotionRecognitionApplication) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_EmotionRecognitionApplication"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_EmotionRecognitionApplication.
func (*IntelSra_ShopperMonitoring_EmotionRecognitionApplication) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState represents the /intel-sra/shopper-monitoring/emotion-recognition-application/model-state YANG schema element.
type IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState struct {
	ActiveModelFile	*string	`path:"active-model-file" module:"intel-sra"`
	ActiveModelName	*string	`path:"active-model-name" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState.
func (*IntelSra_ShopperMonitoring_EmotionRecognitionApplication_ModelState) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_FaceDetectionApplication represents the /intel-sra/shopper-monitoring/face-detection-application YANG schema element.
type IntelSra_ShopperMonitoring_FaceDetectionApplication struct {
	Device	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device	`path:"device" module:"intel-sra"`
	Model	*string	`path:"model" module:"intel-sra"`
	ModelState	*IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState	`path:"model-state" module:"intel-sra"`
	Precision	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision	`path:"precision" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_FaceDetectionApplication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_FaceDetectionApplication) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_FaceDetectionApplication"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_FaceDetectionApplication.
func (*IntelSra_ShopperMonitoring_FaceDetectionApplication) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState represents the /intel-sra/shopper-monitoring/face-detection-application/model-state YANG schema element.
type IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState struct {
	ActiveModelFile	*string	`path:"active-model-file" module:"intel-sra"`
	ActiveModelName	*string	`path:"active-model-name" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState.
func (*IntelSra_ShopperMonitoring_FaceDetectionApplication_ModelState) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_HeadPoseDetectionApplication represents the /intel-sra/shopper-monitoring/head-pose-detection-application YANG schema element.
type IntelSra_ShopperMonitoring_HeadPoseDetectionApplication struct {
	Device	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device	`path:"device" module:"intel-sra"`
	Model	*string	`path:"model" module:"intel-sra"`
	ModelState	*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState	`path:"model-state" module:"intel-sra"`
	Precision	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision	`path:"precision" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_HeadPoseDetectionApplication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_HeadPoseDetectionApplication"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_HeadPoseDetectionApplication.
func (*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState represents the /intel-sra/shopper-monitoring/head-pose-detection-application/model-state YANG schema element.
type IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState struct {
	ActiveModelFile	*string	`path:"active-model-file" module:"intel-sra"`
	ActiveModelName	*string	`path:"active-model-name" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState.
func (*IntelSra_ShopperMonitoring_HeadPoseDetectionApplication_ModelState) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_ShopperMonitoring_RetailArea represents the /intel-sra/shopper-monitoring/retail-area YANG schema element.
type IntelSra_ShopperMonitoring_RetailArea struct {
	AreaRef	*string	`path:"area-ref" module:"intel-sra"`
	Enabled	*bool	`path:"enabled" module:"intel-sra"`
	StreamCount	*uint8	`path:"stream-count" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_ShopperMonitoring_RetailArea implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_ShopperMonitoring_RetailArea) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the IntelSra_ShopperMonitoring_RetailArea struct, which is a YANG list entry.
func (t *IntelSra_ShopperMonitoring_RetailArea) ΛListKeyMap() (map[string]interface{}, error) {
	if t.AreaRef == nil {
		return nil, fmt.Errorf("nil value for key AreaRef")
	}

	return map[string]interface{}{
		"area-ref": *t.AreaRef,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_RetailArea) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_ShopperMonitoring_RetailArea"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_ShopperMonitoring_RetailArea) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_ShopperMonitoring_RetailArea) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_ShopperMonitoring_RetailArea.
func (*IntelSra_ShopperMonitoring_RetailArea) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_StoreTrafficMonitoring represents the /intel-sra/store-traffic-monitoring YANG schema element.
type IntelSra_StoreTrafficMonitoring struct {
	Default	*string	`path:"default" module:"intel-sra"`
	Enable	*bool	`path:"enable" module:"intel-sra"`
	PersonDetectionApplication	*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication	`path:"person-detection-application" module:"intel-sra"`
	RetailArea	map[string]*IntelSra_StoreTrafficMonitoring_RetailArea	`path:"retail-area" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_StoreTrafficMonitoring implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_StoreTrafficMonitoring) IsYANGGoStruct() {}

// NewRetailArea creates a new entry in the RetailArea list of the
// IntelSra_StoreTrafficMonitoring struct. The keys of the list are populated from the input
// arguments.
func (t *IntelSra_StoreTrafficMonitoring) NewRetailArea(AreaRef string) (*IntelSra_StoreTrafficMonitoring_RetailArea, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.RetailArea == nil {
		t.RetailArea = make(map[string]*IntelSra_StoreTrafficMonitoring_RetailArea)
	}

	key := AreaRef

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.RetailArea[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list RetailArea", key)
	}

	t.RetailArea[key] = &IntelSra_StoreTrafficMonitoring_RetailArea{
		AreaRef: &AreaRef,
	}

	return t.RetailArea[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_StoreTrafficMonitoring"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_StoreTrafficMonitoring) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_StoreTrafficMonitoring.
func (*IntelSra_StoreTrafficMonitoring) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_StoreTrafficMonitoring_PersonDetectionApplication represents the /intel-sra/store-traffic-monitoring/person-detection-application YANG schema element.
type IntelSra_StoreTrafficMonitoring_PersonDetectionApplication struct {
	Device	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device	`path:"device" module:"intel-sra"`
	Model	*string	`path:"model" module:"intel-sra"`
	ModelState	*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState	`path:"model-state" module:"intel-sra"`
	Precision	E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision	`path:"precision" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_StoreTrafficMonitoring_PersonDetectionApplication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_StoreTrafficMonitoring_PersonDetectionApplication"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_StoreTrafficMonitoring_PersonDetectionApplication.
func (*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState represents the /intel-sra/store-traffic-monitoring/person-detection-application/model-state YANG schema element.
type IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState struct {
	ActiveModelFile	*string	`path:"active-model-file" module:"intel-sra"`
	ActiveModelName	*string	`path:"active-model-name" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState.
func (*IntelSra_StoreTrafficMonitoring_PersonDetectionApplication_ModelState) ΛBelongingModule() string {
	return "intel-sra"
}


// IntelSra_StoreTrafficMonitoring_RetailArea represents the /intel-sra/store-traffic-monitoring/retail-area YANG schema element.
type IntelSra_StoreTrafficMonitoring_RetailArea struct {
	AreaRef	*string	`path:"area-ref" module:"intel-sra"`
	Enabled	*bool	`path:"enabled" module:"intel-sra"`
	StreamCount	*uint8	`path:"stream-count" module:"intel-sra"`
}

// IsYANGGoStruct ensures that IntelSra_StoreTrafficMonitoring_RetailArea implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*IntelSra_StoreTrafficMonitoring_RetailArea) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the IntelSra_StoreTrafficMonitoring_RetailArea struct, which is a YANG list entry.
func (t *IntelSra_StoreTrafficMonitoring_RetailArea) ΛListKeyMap() (map[string]interface{}, error) {
	if t.AreaRef == nil {
		return nil, fmt.Errorf("nil value for key AreaRef")
	}

	return map[string]interface{}{
		"area-ref": *t.AreaRef,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_RetailArea) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["IntelSra_StoreTrafficMonitoring_RetailArea"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *IntelSra_StoreTrafficMonitoring_RetailArea) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *IntelSra_StoreTrafficMonitoring_RetailArea) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of IntelSra_StoreTrafficMonitoring_RetailArea.
func (*IntelSra_StoreTrafficMonitoring_RetailArea) ΛBelongingModule() string {
	return "intel-sra"
}


// E_IntelSraSource_RetailArea_Location_CoordinateSystem is a derived int64 type which is used to represent
// the enumerated node IntelSraSource_RetailArea_Location_CoordinateSystem. An additional value named
// IntelSraSource_RetailArea_Location_CoordinateSystem_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_IntelSraSource_RetailArea_Location_CoordinateSystem int64

// IsYANGGoEnum ensures that IntelSraSource_RetailArea_Location_CoordinateSystem implements the yang.GoEnum
// interface. This ensures that IntelSraSource_RetailArea_Location_CoordinateSystem can be identified as a
// mapped type for a YANG enumeration.
func (E_IntelSraSource_RetailArea_Location_CoordinateSystem) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  IntelSraSource_RetailArea_Location_CoordinateSystem.
func (E_IntelSraSource_RetailArea_Location_CoordinateSystem) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_IntelSraSource_RetailArea_Location_CoordinateSystem.
func (e E_IntelSraSource_RetailArea_Location_CoordinateSystem) String() string {
	return ygot.EnumLogString(e, int64(e), "E_IntelSraSource_RetailArea_Location_CoordinateSystem")
}

const (
	// IntelSraSource_RetailArea_Location_CoordinateSystem_UNSET corresponds to the value UNSET of IntelSraSource_RetailArea_Location_CoordinateSystem
	IntelSraSource_RetailArea_Location_CoordinateSystem_UNSET E_IntelSraSource_RetailArea_Location_CoordinateSystem = 0
	// IntelSraSource_RetailArea_Location_CoordinateSystem_grid_bottom_left corresponds to the value grid_bottom_left of IntelSraSource_RetailArea_Location_CoordinateSystem
	IntelSraSource_RetailArea_Location_CoordinateSystem_grid_bottom_left E_IntelSraSource_RetailArea_Location_CoordinateSystem = 1
	// IntelSraSource_RetailArea_Location_CoordinateSystem_grid_top_left corresponds to the value grid_top_left of IntelSraSource_RetailArea_Location_CoordinateSystem
	IntelSraSource_RetailArea_Location_CoordinateSystem_grid_top_left E_IntelSraSource_RetailArea_Location_CoordinateSystem = 2
	// IntelSraSource_RetailArea_Location_CoordinateSystem_lat_long corresponds to the value lat_long of IntelSraSource_RetailArea_Location_CoordinateSystem
	IntelSraSource_RetailArea_Location_CoordinateSystem_lat_long E_IntelSraSource_RetailArea_Location_CoordinateSystem = 3
)


// E_IntelSraSource_RetailArea_Source_Video_SourceType is a derived int64 type which is used to represent
// the enumerated node IntelSraSource_RetailArea_Source_Video_SourceType. An additional value named
// IntelSraSource_RetailArea_Source_Video_SourceType_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_IntelSraSource_RetailArea_Source_Video_SourceType int64

// IsYANGGoEnum ensures that IntelSraSource_RetailArea_Source_Video_SourceType implements the yang.GoEnum
// interface. This ensures that IntelSraSource_RetailArea_Source_Video_SourceType can be identified as a
// mapped type for a YANG enumeration.
func (E_IntelSraSource_RetailArea_Source_Video_SourceType) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  IntelSraSource_RetailArea_Source_Video_SourceType.
func (E_IntelSraSource_RetailArea_Source_Video_SourceType) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_IntelSraSource_RetailArea_Source_Video_SourceType.
func (e E_IntelSraSource_RetailArea_Source_Video_SourceType) String() string {
	return ygot.EnumLogString(e, int64(e), "E_IntelSraSource_RetailArea_Source_Video_SourceType")
}

const (
	// IntelSraSource_RetailArea_Source_Video_SourceType_UNSET corresponds to the value UNSET of IntelSraSource_RetailArea_Source_Video_SourceType
	IntelSraSource_RetailArea_Source_Video_SourceType_UNSET E_IntelSraSource_RetailArea_Source_Video_SourceType = 0
	// IntelSraSource_RetailArea_Source_Video_SourceType_file corresponds to the value file of IntelSraSource_RetailArea_Source_Video_SourceType
	IntelSraSource_RetailArea_Source_Video_SourceType_file E_IntelSraSource_RetailArea_Source_Video_SourceType = 1
	// IntelSraSource_RetailArea_Source_Video_SourceType_stream corresponds to the value stream of IntelSraSource_RetailArea_Source_Video_SourceType
	IntelSraSource_RetailArea_Source_Video_SourceType_stream E_IntelSraSource_RetailArea_Source_Video_SourceType = 2
	// IntelSraSource_RetailArea_Source_Video_SourceType_device corresponds to the value device of IntelSraSource_RetailArea_Source_Video_SourceType
	IntelSraSource_RetailArea_Source_Video_SourceType_device E_IntelSraSource_RetailArea_Source_Video_SourceType = 3
	// IntelSraSource_RetailArea_Source_Video_SourceType_sample corresponds to the value sample of IntelSraSource_RetailArea_Source_Video_SourceType
	IntelSraSource_RetailArea_Source_Video_SourceType_sample E_IntelSraSource_RetailArea_Source_Video_SourceType = 4
)


// E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device is a derived int64 type which is used to represent
// the enumerated node IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device. An additional value named
// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device int64

// IsYANGGoEnum ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device implements the yang.GoEnum
// interface. This ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device can be identified as a
// mapped type for a YANG enumeration.
func (E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device.
func (E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device.
func (e E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device) String() string {
	return ygot.EnumLogString(e, int64(e), "E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device")
}

const (
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_UNSET corresponds to the value UNSET of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_UNSET E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device = 0
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_cpu corresponds to the value cpu of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_cpu E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device = 1
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_gpu corresponds to the value gpu of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_gpu E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device = 2
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_vpu corresponds to the value vpu of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device_vpu E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device = 3
)


// E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision is a derived int64 type which is used to represent
// the enumerated node IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision. An additional value named
// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision int64

// IsYANGGoEnum ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision implements the yang.GoEnum
// interface. This ensures that IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision can be identified as a
// mapped type for a YANG enumeration.
func (E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision.
func (E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision.
func (e E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision) String() string {
	return ygot.EnumLogString(e, int64(e), "E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision")
}

const (
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_UNSET corresponds to the value UNSET of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_UNSET E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision = 0
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp8 corresponds to the value fp8 of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp8 E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision = 1
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp16 corresponds to the value fp16 of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp16 E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision = 2
	// IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp32 corresponds to the value fp32 of IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision
	IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision_fp32 E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision = 3
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_IntelSraSource_RetailArea_Location_CoordinateSystem": {
		1: {Name: "grid-bottom-left"},
		2: {Name: "grid-top-left"},
		3: {Name: "lat-long"},
	},
	"E_IntelSraSource_RetailArea_Source_Video_SourceType": {
		1: {Name: "file"},
		2: {Name: "stream"},
		3: {Name: "device"},
		4: {Name: "sample"},
	},
	"E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device": {
		1: {Name: "cpu"},
		2: {Name: "gpu"},
		3: {Name: "vpu"},
	},
	"E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision": {
		1: {Name: "fp8"},
		2: {Name: "fp16"},
		3: {Name: "fp32"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5d, 0xdf, 0x73, 0xdb, 0xb6,
		0x96, 0x7e, 0xcf, 0x5f, 0x71, 0x46, 0x2f, 0x7b, 0xef, 0x8e, 0x65, 0x4b, 0x76, 0x12, 0xbb, 0x7e,
		0xcb, 0x36, 0x69, 0x9b, 0x69, 0xd2, 0x66, 0x92, 0xb4, 0xb3, 0x6d, 0x93, 0xc9, 0xc0, 0x24, 0x24,
		0x63, 0x43, 0x01, 0x1c, 0x10, 0x72, 0xa2, 0xec, 0xe4, 0x7f, 0xbf, 0x43, 0x50, 0xa2, 0x25, 0x51,
		0x24, 0x01, 0x88, 0xb2, 0x65, 0xfb, 0xeb, 0x53, 0x63, 0xe1, 0x80, 0x24, 0x70, 0x7e, 0xe1, 0xe0,
		0xfb, 0x80, 0xff, 0x7f, 0x44, 0x44, 0xd4, 0xfb, 0x8d, 0x4d, 0x78, 0xef, 0x9c, 0x7a, 0x31, 0xbf,
		0x12, 0x11, 0xef, 0x1d, 0x14, 0x7f, 0xfd, 0x55, 0xc8, 0xb8, 0x77, 0x4e, 0xc3, 0xf9, 0x3f, 0x7f,
		0x54, 0x72, 0x24, 0xc6, 0xbd, 0x73, 0x1a, 0xcc, 0xff, 0xf0, 0x5c, 0xe8, 0xde, 0x39, 0x15, 0x5d,
		0xd8, 0x3f, 0x68, 0x6e, 0x98, 0x48, 0xfa, 0x4c, 0x73, 0xb6, 0xf2, 0xc3, 0xca, 0x33, 0x96, 0x1b,
		0x1d, 0xac, 0x36, 0x79, 0xce, 0xb3, 0x48, 0x8b, 0xd4, 0x08, 0x25, 0xf3, 0x96, 0xcf, 0x34, 0x67,
		0x24, 0x32, 0x62, 0x94, 0x5e, 0xce, 0x32, 0x11, 0xb1, 0x84, 0xd2, 0x84, 0x45, 0x9c, 0x84, 0x24,
		0x46, 0x45, 0x3f, 0x94, 0xa8, 0x88, 0xe5, 0x02, 0xc4, 0x0f, 0xc7, 0x87, 0x14, 0xf3, 0x94, 0x69,
		0x33, 0xe1, 0xd2, 0x1c, 0xd0, 0x28, 0x51, 0x4a, 0xaf, 0x3f, 0x62, 0xf5, 0x9b, 0xca, 0x3f, 0xaf,
		0x7f, 0x5b, 0xf9, 0xc3, 0x1b, 0xcd, 0x47, 0xe2, 0x6b, 0xe5, 0x6b, 0x56, 0xbe, 0x28, 0xd3, 0xd1,
		0xda, 0x63, 0xec, 0xcf, 0xef, 0xd4, 0x54, 0x47, 0x7c, 0xa3, 0x68, 0xf1, 0x2a, 0x7c, 0xf6, 0x45,
		0xe9, 0xfc, 0x6d, 0x7a, 0x69, 0xf1, 0x94, 0x83, 0xcd, 0x0d, 0x7f, 0x61, 0xd9, 0x33, 0x3d, 0x9e,
		0xe6, 0x5f, 0xd5, 0x3b, 0x27, 0xa3, 0xa7, 0xbc, 0xa6, 0xe1, 0x52, 0x2b, 0xfb, 0x52, 0x95, 0x56,
		0xdf, 0x57, 0xfe, 0xf2, 0x7d, 0x7d, 0xf8, 0xd7, 0xe6, 0xb3, 0xfc, 0x21, 0x9f, 0xab, 0xbe, 0x88,
		0xeb, 0x3f, 0x65, 0x31, 0x12, 0x8b, 0x86, 0x35, 0xef, 0xb7, 0x3e, 0xbf, 0x92, 0x44, 0xcc, 0xa5,
		0x11, 0x23, 0xc1, 0x35, 0x8d, 0x94, 0x26, 0x73, 0xc9, 0x17, 0xf3, 0xba, 0x41, 0x3f, 0xd6, 0x27,
		0x71, 0x50, 0xf3, 0x73, 0xdd, 0x64, 0xba, 0x4c, 0xaa, 0xe3, 0xe4, 0xba, 0x4e, 0xb2, 0xf7, 0x64,
		0x7b, 0x4f, 0xba, 0xfb, 0xe4, 0x6f, 0x56, 0x82, 0x1a, 0x65, 0x28, 0xbb, 0x7d, 0x3f, 0x4b, 0xb9,
		0xe3, 0x48, 0x19, 0x2d, 0xe4, 0xb8, 0x69, 0xb0, 0x16, 0xc6, 0x77, 0xd6, 0xd0, 0xe6, 0x15, 0x97,
		0x63, 0x73, 0xd9, 0x3b, 0xa7, 0x7f, 0x1a, 0x3f, 0xb7, 0x79, 0xb8, 0x6d, 0x4f, 0xaf, 0x85, 0x6c,
		0x9d, 0x97, 0xb2, 0xf1, 0x9f, 0x2c, 0x99, 0xf2, 0xaa, 0x63, 0xa8, 0x6d, 0xff, 0x93, 0x66, 0x51,
		0xae, 0xc7, 0xcf, 0xc5, 0x58, 0x98, 0xac, 0x5e, 0xd7, 0xaa, 0xa3, 0xc5, 0xc7, 0xcc, 0x88, 0xab,
		0xfc, 0x59, 0x23, 0x96, 0x64, 0xbc, 0x55, 0xea, 0xfb, 0x81, 0xc3, 0xa7, 0xb2, 0xaf, 0xfe, 0x9f,
		0x7a, 0x36, 0xd8, 0xbf, 0x6f, 0x7d, 0x14, 0xf6, 0xeb, 0xc7, 0x47, 0x6e, 0xed, 0x37, 0x8c, 0x65,
		0x2f, 0x5e, 0x71, 0x4a, 0x2d, 0x0e, 0x6e, 0xb9, 0xb1, 0x9b, 0x93, 0x4b, 0x94, 0x1c, 0xd3, 0x92,
		0x18, 0x8d, 0x04, 0x4f, 0x62, 0x78, 0x36, 0x78, 0x36, 0x78, 0xb6, 0x5d, 0x79, 0xb6, 0xe1, 0xe0,
		0xf8, 0x31, 0x7c, 0x5b, 0xee, 0xdb, 0x44, 0x96, 0x26, 0x6c, 0xd6, 0x97, 0x85, 0x22, 0xb7, 0x39,
		0xb7, 0xe5, 0xd6, 0x6e, 0xde, 0x6d, 0x2e, 0x42, 0xb9, 0x08, 0x19, 0x45, 0xd3, 0xcc, 0x66, 0xe7,
		0x3f, 0xff, 0xf1, 0x92, 0x94, 0xa6, 0x1f, 0x5f, 0xbd, 0x84, 0xa3, 0x83, 0xa3, 0x83, 0xa3, 0x43,
		0x0a, 0xb7, 0x53, 0x37, 0x27, 0x26, 0x6c, 0xec, 0xe0, 0xdf, 0x8a, 0x66, 0x6e, 0x8e, 0x8d, 0xd1,
		0x1f, 0x6f, 0x5f, 0xe5, 0x1e, 0x8d, 0x49, 0xb2, 0x72, 0x34, 0x12, 0x09, 0xa7, 0x7f, 0xd9, 0x2a,
		0xc3, 0xbb, 0x3f, 0x7f, 0x3e, 0xa0, 0x37, 0xbf, 0xfd, 0xfc, 0xef, 0x43, 0xfa, 0xdd, 0x4a, 0xb0,
		0x04, 0x7e, 0x0e, 0x7e, 0x0e, 0x7e, 0x6e, 0x57, 0x7e, 0xee, 0x78, 0x00, 0x47, 0x97, 0xbf, 0xe4,
		0xa2, 0xd8, 0xd9, 0xee, 0xeb, 0xca, 0x96, 0x6e, 0xee, 0xae, 0x2c, 0xb0, 0x96, 0xe5, 0x54, 0x21,
		0x69, 0xac, 0x45, 0x9c, 0xa7, 0x71, 0x09, 0x33, 0xc2, 0x4c, 0x63, 0x4e, 0x4c, 0xc6, 0x94, 0xaf,
		0x67, 0xed, 0xbf, 0x5a, 0x3c, 0xde, 0x10, 0x1e, 0x6f, 0xf7, 0x1e, 0xaf, 0xae, 0x62, 0x5b, 0x36,
		0x88, 0x94, 0xd2, 0xb1, 0x90, 0xcc, 0xf0, 0x7e, 0x36, 0xcb, 0x0c, 0x9f, 0xb4, 0x0f, 0xc6, 0x62,
		0x6c, 0xab, 0xa2, 0x2d, 0xdf, 0xb8, 0xa6, 0x52, 0xd1, 0xa5, 0x12, 0x11, 0x27, 0x35, 0xa2, 0xeb,
		0x9e, 0xc8, 0xad, 0xa7, 0xe6, 0xa0, 0xe9, 0xac, 0x4a, 0x3e, 0x2a, 0xe5, 0xa9, 0x5a, 0xbe, 0x2a,
		0x16, 0xac, 0x6a, 0xc1, 0x2a, 0xe7, 0xaf, 0x7a, 0x8e, 0x8e, 0xad, 0x65, 0xac, 0x5f, 0x33, 0x19,
		0x33, 0xa3, 0xf4, 0xac, 0x3d, 0x42, 0xb5, 0x07, 0xec, 0xca, 0xac, 0x70, 0x39, 0x9d, 0x70, 0xdd,
		0xe4, 0xd9, 0x36, 0xfa, 0x22, 0x87, 0x6a, 0x40, 0xef, 0x85, 0x9c, 0x4e, 0xdc, 0xe7, 0xf1, 0xbd,
		0x7a, 0x57, 0xe4, 0x10, 0xae, 0x12, 0x56, 0x6a, 0x90, 0x7f, 0x43, 0xee, 0x56, 0xfb, 0x17, 0xca,
		0x18, 0x35, 0xe9, 0x27, 0x7c, 0x64, 0x1c, 0x35, 0xc0, 0x76, 0x30, 0x2c, 0x3b, 0x30, 0x2a, 0xf5,
		0x96, 0x3e, 0xb6, 0x91, 0x81, 0x99, 0x7e, 0xee, 0xc4, 0x7b, 0x4e, 0x72, 0xdf, 0x0f, 0x5c, 0xc7,
		0xe3, 0xa5, 0x55, 0x31, 0x8f, 0xc1, 0xa8, 0x8c, 0x83, 0x73, 0xb0, 0xbe, 0x16, 0x2f, 0x47, 0xc1,
		0x39, 0x1d, 0x2a, 0xe2, 0xe8, 0x62, 0x0c, 0xce, 0xe9, 0xd8, 0x6d, 0x18, 0x76, 0x96, 0x0e, 0x34,
		0x0c, 0x70, 0x4f, 0x69, 0xc1, 0xa5, 0xb1, 0xda, 0xde, 0xff, 0xea, 0xee, 0xb9, 0x57, 0xc5, 0xfc,
		0xbc, 0xb6, 0x56, 0xa6, 0x8c, 0xff, 0xf1, 0x58, 0x73, 0x9e, 0xd9, 0x4d, 0xb9, 0xff, 0xed, 0xff,
		0x45, 0x69, 0xc2, 0x24, 0xa7, 0x28, 0x51, 0xd1, 0xe7, 0x2f, 0x22, 0xe3, 0x34, 0xd2, 0x6a, 0x62,
		0x7f, 0x3c, 0x21, 0xf5, 0x5f, 0xf6, 0xcf, 0x94, 0xaa, 0x4c, 0x38, 0xd8, 0x26, 0x1c, 0xfc, 0x1d,
		0x76, 0xf0, 0xfe, 0x4e, 0x5b, 0x48, 0xf3, 0xf4, 0xb1, 0x87, 0xbb, 0x76, 0xf1, 0xd6, 0x6f, 0x99,
		0xb4, 0x4b, 0xfe, 0x7f, 0x9c, 0xc6, 0xc8, 0xc3, 0x2b, 0xf9, 0x2c, 0xc5, 0x2a, 0xeb, 0x94, 0x1f,
		0x8e, 0x8f, 0x4f, 0x4e, 0x4e, 0x8f, 0x07, 0x27, 0x4f, 0xcf, 0x9e, 0x3c, 0x3e, 0x3d, 0x7d, 0x72,
		0x36, 0x38, 0x3b, 0xf0, 0xeb, 0x29, 0x74, 0xfd, 0xb2, 0x69, 0x1d, 0x93, 0xeb, 0x90, 0xb3, 0xf0,
		0x77, 0x0f, 0xf7, 0xe9, 0xb3, 0x86, 0x73, 0x18, 0xa3, 0xd3, 0x5b, 0x1c, 0x23, 0xb7, 0xb5, 0x9e,
		0x7b, 0x18, 0x70, 0x6b, 0xf5, 0x71, 0x07, 0xc1, 0xc2, 0x23, 0x40, 0xf8, 0x06, 0x85, 0xf7, 0x79,
		0x04, 0x28, 0x9d, 0xfb, 0xca, 0xd2, 0x70, 0xb1, 0x1a, 0xa4, 0x8b, 0x19, 0x0d, 0x07, 0xbc, 0x7f,
		0x0a, 0xd7, 0x8f, 0xdc, 0x1e, 0x61, 0x02, 0x61, 0x02, 0x61, 0x62, 0x3f, 0xc3, 0xc4, 0xcc, 0x3d,
		0x4c, 0xcc, 0x02, 0xc2, 0xc4, 0x5f, 0x9b, 0xc3, 0xc4, 0xa2, 0x82, 0x88, 0x28, 0x81, 0x28, 0x81,
		0x28, 0x81, 0x28, 0x81, 0x28, 0xb1, 0xdf, 0x51, 0xe2, 0x9b, 0x7b, 0x94, 0xf8, 0x16, 0x10, 0x25,
		0xfe, 0xde, 0x18, 0x25, 0x78, 0xc2, 0xaf, 0xca, 0xe2, 0x53, 0xc4, 0xa5, 0x11, 0x13, 0x6e, 0x34,
		0xcf, 0xe8, 0x5f, 0x6a, 0xbe, 0xcb, 0xfe, 0x6f, 0xc4, 0x0d, 0x14, 0x96, 0x10, 0x0b, 0x10, 0x0b,
		0x10, 0x0b, 0x3a, 0x8e, 0x05, 0x5e, 0xdb, 0xce, 0xfc, 0xab, 0xd1, 0xac, 0x3f, 0x95, 0x99, 0x61,
		0x17, 0x49, 0x0b, 0xe4, 0x26, 0xd5, 0x3c, 0xe3, 0x32, 0xe2, 0x5d, 0xc0, 0x64, 0x16, 0x76, 0x9f,
		0xeb, 0xdf, 0xee, 0x5d, 0x6c, 0xf1, 0xda, 0x37, 0xe9, 0x64, 0xed, 0x77, 0xdd, 0x34, 0xf0, 0xa4,
		0x8e, 0x4b, 0x26, 0xe5, 0x7c, 0x2b, 0xa8, 0x79, 0x7e, 0xb3, 0xe8, 0x92, 0x4f, 0x58, 0xca, 0x2c,
		0x10, 0xaa, 0x77, 0x24, 0xa4, 0xe1, 0x49, 0x3f, 0xd3, 0xac, 0x9f, 0xd9, 0xc1, 0x3f, 0x5a, 0xa2,
		0xfb, 0x1d, 0xb5, 0x80, 0x52, 0x8a, 0xfe, 0x8c, 0x9e, 0x46, 0x66, 0x0e, 0x58, 0xee, 0xbd, 0xcc,
		0xbb, 0x7b, 0xa7, 0x59, 0x31, 0x93, 0x9f, 0xde, 0xda, 0xce, 0x9e, 0x69, 0xce, 0x3e, 0xbd, 0x5a,
		0xf4, 0xb5, 0x05, 0x9c, 0x26, 0x6b, 0x61, 0xe8, 0x95, 0x11, 0xbd, 0x68, 0xe7, 0x06, 0xa5, 0xc9,
		0xf3, 0x9b, 0x44, 0x64, 0xc6, 0x22, 0x1f, 0xd8, 0x84, 0x6b, 0x96, 0x01, 0x2a, 0x73, 0x07, 0xa0,
		0x32, 0x2e, 0x3c, 0xa0, 0xca, 0xa8, 0xb6, 0xf3, 0x81, 0xea, 0xd4, 0xc4, 0x8b, 0x17, 0x84, 0xfc,
		0xf6, 0x41, 0xe6, 0xb7, 0xad, 0x30, 0xd5, 0x8a, 0x27, 0x71, 0xc8, 0x0a, 0x5d, 0x61, 0xab, 0x37,
		0x9d, 0xe2, 0x0e, 0xef, 0x4e, 0xb2, 0x76, 0x53, 0x19, 0xad, 0x3b, 0x8f, 0x09, 0x29, 0x6c, 0x63,
		0x39, 0xc3, 0x89, 0x07, 0x55, 0x75, 0xee, 0xed, 0x7c, 0xa8, 0x3a, 0xef, 0x1e, 0xca, 0x8b, 0x82,
		0xa3, 0x87, 0xa3, 0x87, 0xa3, 0x7f, 0x70, 0x8e, 0xfe, 0x6c, 0x00, 0x37, 0xdf, 0x81, 0x9b, 0x6f,
		0xe6, 0x81, 0x55, 0xcb, 0x87, 0x0d, 0x7c, 0xb0, 0x3a, 0xc7, 0xde, 0x11, 0x2f, 0x0c, 0x7e, 0x1e,
		0x7e, 0x1e, 0x7e, 0xfe, 0xc1, 0xf9, 0x79, 0x67, 0x1e, 0x1b, 0x1c, 0x7d, 0xa3, 0xa3, 0x6f, 0xe5,
		0xc1, 0x55, 0x2c, 0xcf, 0xa1, 0xf4, 0x48, 0x3b, 0xe5, 0xc5, 0x39, 0x16, 0xfd, 0xe0, 0xf1, 0xf7,
		0xd9, 0xe3, 0xb7, 0x15, 0x11, 0xcb, 0x86, 0xfe, 0xbc, 0xbb, 0xca, 0x1c, 0xf9, 0xf2, 0xef, 0xea,
		0x54, 0x38, 0x9c, 0x87, 0xe7, 0x99, 0xa4, 0x78, 0xab, 0x6e, 0x88, 0x0a, 0x07, 0xaa, 0x72, 0xa8,
		0x4a, 0x6f, 0xad, 0xda, 0x5b, 0xab, 0x78, 0xb8, 0xaa, 0x7b, 0x3a, 0x72, 0xc7, 0xb9, 0xf2, 0x40,
		0x77, 0xf9, 0x27, 0x4a, 0x95, 0xd9, 0xf5, 0xe3, 0xfb, 0x55, 0x7c, 0xac, 0x47, 0xf5, 0xcc, 0x8f,
		0xff, 0x77, 0xfd, 0x69, 0x21, 0x3c, 0xc0, 0x52, 0x7a, 0x5b, 0x3e, 0x60, 0xd9, 0xd1, 0x56, 0xbc,
		0xc0, 0xb2, 0x97, 0x00, 0x7e, 0x60, 0x40, 0x0a, 0x45, 0x61, 0x7c, 0xc1, 0x52, 0x74, 0x3b, 0xde,
		0xe0, 0x6a, 0x37, 0x61, 0xfc, 0xc1, 0xeb, 0x3c, 0xc4, 0x97, 0x47, 0xe8, 0x67, 0x93, 0x5d, 0xa6,
		0x61, 0x2e, 0x67, 0x33, 0xf8, 0xf1, 0x0d, 0x2b, 0xc6, 0xea, 0xc3, 0x3b, 0xac, 0x8b, 0x56, 0x37,
		0xc2, 0x3f, 0x44, 0x60, 0x43, 0x60, 0xeb, 0x30, 0x48, 0xb9, 0xc2, 0xd0, 0xd6, 0xd5, 0xce, 0x27,
		0x3a, 0xf9, 0xc1, 0xd2, 0xfc, 0x97, 0xfa, 0x5b, 0x2d, 0xf9, 0x2b, 0xeb, 0xdc, 0xad, 0xe1, 0x6a,
		0x9d, 0xad, 0x7f, 0x37, 0xad, 0x83, 0xbd, 0xe0, 0x6b, 0x81, 0x01, 0x2e, 0xb8, 0x56, 0xe0, 0x30,
		0x96, 0xa7, 0x7b, 0x34, 0x96, 0x7e, 0x35, 0x05, 0xff, 0xf0, 0xe7, 0xd7, 0xfa, 0xe3, 0x0d, 0x06,
		0xcb, 0x80, 0x00, 0x19, 0x1a, 0x14, 0x3b, 0xe4, 0x5f, 0x22, 0xf4, 0x21, 0xf4, 0xdd, 0xf2, 0x9a,
		0x0e, 0xe1, 0x12, 0xe1, 0x12, 0xe1, 0xf2, 0xa1, 0x85, 0xcb, 0x99, 0x7f, 0xb8, 0x9c, 0x6d, 0x11,
		0x2e, 0xbb, 0xe1, 0xa1, 0x22, 0x5a, 0x22, 0x5a, 0x22, 0x5a, 0x22, 0x5a, 0x22, 0x5a, 0x22, 0x5a,
		0xde, 0x68, 0xb4, 0xfc, 0xe6, 0x1f, 0x2d, 0xbf, 0x6d, 0x11, 0x2d, 0x77, 0xc5, 0xc7, 0x45, 0xfc,
		0x44, 0xfc, 0x44, 0x2c, 0x44, 0x2c, 0x44, 0x2c, 0x44, 0x2c, 0x0c, 0x68, 0xd1, 0x06, 0xc7, 0xf1,
		0xe0, 0x21, 0x97, 0x32, 0xce, 0x7c, 0x64, 0x7f, 0xd3, 0xf6, 0xe5, 0x27, 0x77, 0x1c, 0x52, 0x7c,
		0xf8, 0xca, 0xbb, 0x09, 0x2a, 0x6e, 0xfc, 0x65, 0xcf, 0xa8, 0xb2, 0x2d, 0xc0, 0xb0, 0x8d, 0x6e,
		0xea, 0xc6, 0x73, 0x2e, 0xdb, 0xfb, 0xf0, 0x9d, 0xe7, 0x7f, 0x72, 0xc4, 0x1e, 0x92, 0x0f, 0xfd,
		0x79, 0xfe, 0x97, 0x66, 0x16, 0x74, 0xfb, 0x18, 0x36, 0x81, 0x2c, 0x8b, 0xb7, 0x6f, 0xba, 0xf7,
		0xb3, 0x9a, 0x4a, 0x95, 0x22, 0x7e, 0x30, 0x4b, 0x73, 0xc9, 0x0b, 0xaa, 0x94, 0x1a, 0xd9, 0x1d,
		0x7d, 0x21, 0x47, 0x5c, 0xe7, 0xea, 0x4c, 0x8d, 0xd4, 0x6b, 0xcf, 0xf4, 0x12, 0x98, 0xca, 0xdd,
		0xa4, 0x89, 0x77, 0x00, 0x45, 0xbf, 0x0b, 0xf3, 0x30, 0xcc, 0x78, 0x90, 0x4d, 0x8a, 0xe6, 0x9e,
		0x87, 0x71, 0x73, 0x16, 0x93, 0x92, 0xc9, 0x8c, 0x98, 0x31, 0x5a, 0x5c, 0x4c, 0x0d, 0xcf, 0x16,
		0x26, 0x52, 0x18, 0x06, 0xf5, 0x29, 0x55, 0xe9, 0x34, 0x61, 0x86, 0xc7, 0x74, 0x31, 0x23, 0x16,
		0xb3, 0xd4, 0x70, 0x5d, 0x60, 0x63, 0x98, 0x64, 0xc9, 0xcc, 0x88, 0x28, 0x23, 0x2e, 0xc7, 0x42,
		0x76, 0x8e, 0x4c, 0x3e, 0x86, 0x15, 0xed, 0x8d, 0x15, 0x39, 0x23, 0x93, 0xb9, 0xd6, 0x4a, 0xfb,
		0x57, 0x17, 0x0a, 0xb1, 0xb0, 0x0a, 0xc3, 0xf2, 0x29, 0x07, 0x6a, 0x44, 0xb6, 0x2b, 0x12, 0x23,
		0x2a, 0x72, 0x16, 0x83, 0x1a, 0x02, 0x6a, 0x08, 0x37, 0x57, 0x43, 0x70, 0x0e, 0x1e, 0x9e, 0x41,
		0xa4, 0xdb, 0xfa, 0x9f, 0xb5, 0x91, 0x7e, 0x26, 0xa4, 0x8f, 0x93, 0x5b, 0xb1, 0xd5, 0xb9, 0x70,
		0xa0, 0xc5, 0x32, 0x53, 0xb0, 0x5a, 0x8c, 0x98, 0xf0, 0xb9, 0xc1, 0x26, 0x2c, 0x33, 0x34, 0x4d,
		0xf3, 0x9f, 0x62, 0x98, 0x2c, 0x4c, 0x16, 0x26, 0x5b, 0xcd, 0x07, 0xa7, 0x99, 0xbf, 0xb5, 0xce,
		0xe5, 0xc2, 0x0c, 0xb5, 0x10, 0x5e, 0xcd, 0x09, 0x61, 0x9c, 0x30, 0xce, 0x07, 0x65, 0x9c, 0xfb,
		0x5e, 0xff, 0x71, 0x59, 0xfa, 0x85, 0x14, 0x7f, 0xde, 0xd9, 0x7e, 0x77, 0xb0, 0xb4, 0xbd, 0x12,
		0x31, 0x57, 0xee, 0x4b, 0xdb, 0xa2, 0xb9, 0xe7, 0x39, 0x0a, 0xd7, 0x0b, 0x5a, 0xcd, 0x8b, 0xe5,
		0xab, 0x51, 0x64, 0x7b, 0xa2, 0xcc, 0x68, 0xce, 0x26, 0xe0, 0xd1, 0x62, 0xb5, 0xda, 0x9b, 0xdb,
		0x99, 0x67, 0x48, 0xb5, 0x52, 0x61, 0x01, 0x35, 0x0f, 0xa3, 0xb9, 0x78, 0xae, 0x8d, 0x01, 0x95,
		0x48, 0x04, 0x57, 0x04, 0xd7, 0xca, 0x6b, 0xdc, 0x2c, 0x60, 0x6c, 0x8b, 0x80, 0xec, 0x21, 0xe3,
		0x79, 0xe6, 0xc8, 0xe2, 0xbf, 0xdb, 0xda, 0x27, 0x1f, 0xde, 0xfd, 0x9d, 0xdc, 0xdb, 0xda, 0x16,
		0x1f, 0x0e, 0x06, 0xd8, 0x06, 0xaf, 0xf9, 0xef, 0xa3, 0x87, 0xc5, 0xbc, 0x61, 0xc6, 0x70, 0x2d,
		0xbd, 0x4d, 0xa6, 0xf7, 0x0f, 0xeb, 0x7f, 0x7b, 0xd6, 0xff, 0x7b, 0xd0, 0xff, 0xe1, 0xc3, 0x87,
		0xc3, 0xa3, 0x4f, 0xe7, 0xfd, 0x8f, 0xff, 0xdd, 0xdb, 0x4b, 0xd0, 0xda, 0x7c, 0xf7, 0xcf, 0xf8,
		0xb8, 0xae, 0xf5, 0xad, 0x43, 0x2b, 0x1c, 0x16, 0xba, 0x8b, 0x38, 0x45, 0x3e, 0x3d, 0x20, 0x4a,
		0x23, 0x4a, 0xdf, 0x4e, 0x94, 0x7e, 0x08, 0x07, 0x5b, 0x8c, 0x44, 0xc2, 0x83, 0x0f, 0xb3, 0x70,
		0x5a, 0x04, 0x6e, 0x14, 0x3f, 0x2e, 0xf6, 0x9c, 0xae, 0x44, 0x14, 0xf4, 0xf4, 0x13, 0xfb, 0x74,
		0x36, 0x49, 0x13, 0xbe, 0xb7, 0x47, 0x60, 0xcc, 0xbf, 0xae, 0x75, 0x0b, 0x76, 0xa3, 0xb0, 0x9d,
		0x96, 0xb0, 0x33, 0x33, 0xe6, 0xc3, 0x72, 0x4e, 0x27, 0x21, 0xc2, 0xc5, 0x8c, 0x9e, 0xd3, 0x70,
		0xdf, 0x8f, 0xca, 0xd8, 0xf7, 0x82, 0x92, 0x4b, 0xc1, 0x25, 0xa4, 0xa0, 0xf4, 0xa7, 0xed, 0xf7,
		0x46, 0xae, 0x10, 0xf9, 0x95, 0xcf, 0x5c, 0x00, 0x43, 0xbd, 0x57, 0x22, 0x33, 0xcf, 0x8c, 0x69,
		0x39, 0xbb, 0xff, 0xb5, 0x90, 0x2f, 0x12, 0x9e, 0x07, 0x91, 0x96, 0x34, 0x33, 0x4f, 0x89, 0x97,
		0x5a, 0x0e, 0xcf, 0x1e, 0x3f, 0x7e, 0x7a, 0xfa, 0xf8, 0xf1, 0xe0, 0xf4, 0xe4, 0x74, 0xf0, 0xc3,
		0x93, 0x27, 0xc3, 0xa7, 0xc3, 0x27, 0x0d, 0xc2, 0xbf, 0xeb, 0x98, 0x6b, 0x1e, 0xff, 0x4f, 0xfe,
		0xea, 0x72, 0x9a, 0x24, 0xb7, 0x7e, 0xa1, 0x46, 0x6b, 0x4d, 0xc2, 0x53, 0x03, 0x9c, 0x2f, 0xd3,
		0x78, 0xd4, 0xf0, 0xc5, 0x8b, 0xb9, 0xcd, 0xdf, 0xb0, 0x3a, 0xb3, 0xcd, 0x33, 0xda, 0x3e, 0x93,
		0x41, 0x33, 0xd8, 0x3c, 0x73, 0xeb, 0xef, 0xdf, 0x32, 0x53, 0x3e, 0x33, 0xd4, 0xdb, 0x74, 0xeb,
		0x88, 0xdb, 0x94, 0xac, 0xce, 0xc5, 0xf5, 0x88, 0x2f, 0xbd, 0x6d, 0x2f, 0xbb, 0xe4, 0xc9, 0xa8,
		0x3f, 0x51, 0x52, 0x18, 0xb5, 0x31, 0x58, 0x5f, 0x67, 0x93, 0xeb, 0x2d, 0xd7, 0xbe, 0x79, 0x2d,
		0x97, 0x2e, 0x32, 0xdd, 0xa9, 0xe6, 0xf4, 0x2c, 0x4d, 0x13, 0x31, 0x3f, 0xfb, 0xd0, 0x28, 0x8a,
		0xd4, 0x54, 0x1a, 0x52, 0x17, 0xff, 0xc7, 0x23, 0x93, 0x91, 0x90, 0x64, 0x3b, 0x5e, 0xef, 0x6d,
		0x73, 0x6d, 0xb6, 0x36, 0x7f, 0x6e, 0xca, 0x93, 0x97, 0xf2, 0xe1, 0x8d, 0xa3, 0xd9, 0x92, 0xf7,
		0x3a, 0xe7, 0xb7, 0xce, 0x79, 0xec, 0x5a, 0xbe, 0xca, 0x7a, 0x9e, 0xd6, 0x51, 0x57, 0xfb, 0xec,
		0xc5, 0x7c, 0xc4, 0xa6, 0x89, 0x69, 0xbf, 0x8e, 0x66, 0xd1, 0xd0, 0xed, 0x3e, 0x9a, 0x09, 0xd3,
		0x9f, 0x6d, 0x29, 0x73, 0x2e, 0xd6, 0x5c, 0xc8, 0x6c, 0x59, 0x12, 0x75, 0x7d, 0x27, 0x0d, 0xbb,
		0x8b, 0x77, 0xd2, 0xb0, 0xae, 0xee, 0xa4, 0x69, 0x5d, 0x3e, 0x5c, 0x1f, 0x5f, 0xca, 0xd9, 0x48,
		0xf3, 0x51, 0xd3, 0x68, 0x2d, 0x6c, 0xae, 0x81, 0xb4, 0xd0, 0x7b, 0xb3, 0xf0, 0x59, 0x99, 0x8e,
		0xce, 0x57, 0x02, 0x89, 0x8e, 0xce, 0x17, 0xbb, 0x55, 0xe5, 0xff, 0xe6, 0xce, 0x7b, 0x8b, 0xdb,
		0x95, 0xb8, 0x6c, 0x44, 0xe5, 0x2f, 0x2d, 0x85, 0x6c, 0x3b, 0x37, 0x6d, 0x7e, 0x23, 0x52, 0x9e,
		0x08, 0xc9, 0xa9, 0x90, 0x8a, 0xa1, 0xc6, 0xb7, 0xaf, 0xc6, 0x0e, 0x2b, 0x67, 0x0f, 0x55, 0xbf,
		0x50, 0x2a, 0xe1, 0x4c, 0xba, 0xa8, 0xfa, 0x70, 0x0b, 0xed, 0x2c, 0x42, 0x58, 0x3f, 0xe6, 0x86,
		0xdb, 0x22, 0x65, 0x9f, 0x5d, 0x07, 0xba, 0x76, 0x9d, 0x6d, 0x94, 0x76, 0xd3, 0xe4, 0x68, 0x1e,
		0x62, 0xd9, 0x02, 0x17, 0xf9, 0xbb, 0xed, 0x93, 0x9e, 0x2f, 0xfa, 0xdc, 0x8f, 0x5b, 0xc3, 0x1e,
		0xb6, 0x6a, 0x3b, 0xdc, 0x1a, 0x36, 0x5f, 0x89, 0x3b, 0x5f, 0x18, 0xe6, 0x50, 0x97, 0xa8, 0x64,
		0x63, 0xe5, 0x11, 0xbe, 0x52, 0xc5, 0x79, 0x20, 0x77, 0xe9, 0x63, 0x3f, 0x38, 0x11, 0xec, 0x3e,
		0xee, 0x8f, 0xb3, 0xbb, 0x7d, 0x85, 0xba, 0x5f, 0xed, 0xd1, 0xa7, 0xe6, 0xe8, 0x57, 0x6b, 0x0c,
		0xab, 0x31, 0x16, 0xe5, 0xc1, 0x28, 0x9d, 0xfa, 0xd4, 0x4d, 0x6d, 0x4d, 0x70, 0xec, 0x27, 0x63,
		0x0b, 0x81, 0x57, 0xe9, 0xb4, 0xd7, 0x2d, 0xd2, 0xca, 0xbb, 0xea, 0x67, 0xbf, 0xd5, 0x6b, 0x0b,
		0xd3, 0x7e, 0xa9, 0x57, 0x71, 0xd0, 0x7e, 0xe7, 0x39, 0x9d, 0xdc, 0x4c, 0x05, 0x2d, 0x08, 0x94,
		0x34, 0x51, 0x31, 0x4f, 0xdc, 0x1d, 0x6d, 0xd1, 0xdc, 0xcf, 0xcf, 0xbe, 0x90, 0x86, 0x6b, 0xb2,
		0x92, 0x96, 0x8e, 0x76, 0x48, 0xaf, 0x38, 0xbb, 0xe2, 0x74, 0x91, 0x30, 0xf9, 0x79, 0x71, 0x8d,
		0xd7, 0xf2, 0x52, 0xca, 0x36, 0x3d, 0xfc, 0x20, 0x5f, 0xca, 0x2b, 0x96, 0x88, 0x98, 0xae, 0x58,
		0x32, 0xe5, 0x19, 0x7d, 0x11, 0x49, 0x42, 0x17, 0x9c, 0xc4, 0x58, 0x2a, 0xcd, 0xe3, 0x02, 0x49,
		0xbd, 0x24, 0xb6, 0xd6, 0x6c, 0x9a, 0xf1, 0x98, 0x84, 0xcc, 0x0c, 0x67, 0xf1, 0xe1, 0x07, 0xf9,
		0xfe, 0x52, 0x64, 0x24, 0x32, 0x62, 0x92, 0xf8, 0x57, 0x5b, 0x70, 0xcd, 0x3d, 0x3f, 0xa3, 0x44,
		0xa9, 0x8c, 0x27, 0xb3, 0x7c, 0x09, 0x9e, 0x26, 0x79, 0xaf, 0x0b, 0x08, 0xd5, 0x21, 0x59, 0x24,
		0xd8, 0xa2, 0x5b, 0xa6, 0x39, 0x49, 0xce, 0x63, 0x1e, 0xd3, 0x05, 0x4f, 0xd4, 0x97, 0x0f, 0xd2,
		0x28, 0xca, 0x2e, 0xd5, 0x17, 0xfb, 0x0e, 0x2c, 0x32, 0x53, 0x96, 0x90, 0xe6, 0x59, 0xfe, 0x26,
		0x73, 0xe0, 0xe8, 0x4a, 0x2e, 0x82, 0xc0, 0x72, 0x7f, 0x03, 0x0b, 0xae, 0xac, 0xd9, 0x28, 0x84,
		0x2b, 0x6b, 0xea, 0x87, 0x04, 0x57, 0xd6, 0x74, 0x17, 0xbe, 0xfa, 0x9e, 0xa4, 0xd1, 0x65, 0xa1,
		0x50, 0xea, 0xe8, 0x22, 0x2a, 0x5c, 0xa8, 0xa9, 0xb1, 0xce, 0xde, 0x76, 0x9a, 0x91, 0x53, 0xaf,
		0xfb, 0x41, 0x09, 0x85, 0xaf, 0x0f, 0xf1, 0xf5, 0xce, 0x20, 0xdb, 0xdc, 0x5c, 0xaf, 0x78, 0xbf,
		0x50, 0xb6, 0xf9, 0xee, 0xb0, 0x27, 0x7a, 0xa7, 0xda, 0x45, 0xf8, 0x61, 0x54, 0xf6, 0x42, 0xbd,
		0xe5, 0xd3, 0x00, 0x8a, 0x84, 0x4c, 0x48, 0x9b, 0x7e, 0x2d, 0x92, 0xa6, 0x3c, 0xa1, 0x91, 0x74,
		0xc9, 0xf5, 0x3d, 0x01, 0xfb, 0xb0, 0x87, 0x08, 0xf6, 0x61, 0xe0, 0xbb, 0x04, 0x2c, 0xae, 0x0e,
		0x3c, 0x4d, 0xda, 0xe9, 0xd6, 0xe3, 0x66, 0x93, 0x76, 0xb8, 0x02, 0xb9, 0xc9, 0xa4, 0x61, 0xc1,
		0xb0, 0x60, 0x58, 0x70, 0x47, 0x71, 0xbd, 0x2b, 0x80, 0xd1, 0xd1, 0x3a, 0x26, 0xe0, 0xa8, 0x69,
		0x57, 0xe3, 0xc8, 0x3d, 0x17, 0xa5, 0x7a, 0x94, 0xc3, 0xa7, 0x77, 0xf9, 0x33, 0x5f, 0x97, 0x8f,
		0xfc, 0x54, 0x6c, 0x7a, 0x94, 0x7b, 0x1e, 0x4b, 0x68, 0x83, 0x4f, 0xaf, 0xf3, 0x07, 0xee, 0x8c,
		0xe3, 0x96, 0x6a, 0x1e, 0x89, 0xcc, 0xeb, 0x0e, 0xc9, 0x6b, 0x11, 0x94, 0xef, 0x91, 0x79, 0xa3,
		0x7c, 0xbf, 0x45, 0xf9, 0x7e, 0x94, 0x9e, 0x79, 0x97, 0xef, 0x47, 0xe9, 0xf0, 0xa9, 0x77, 0xfd,
		0x7e, 0x94, 0x9e, 0x1c, 0xdf, 0x7a, 0x01, 0xdf, 0xbe, 0xb9, 0x5f, 0x3d, 0xde, 0xbe, 0xb7, 0x17,
		0xce, 0xd6, 0x8e, 0xa9, 0x2b, 0xb8, 0x76, 0x87, 0x25, 0xfc, 0x1b, 0x05, 0x45, 0xfa, 0xc5, 0x30,
		0x7f, 0xa0, 0xa4, 0x47, 0xbc, 0xda, 0x06, 0x2a, 0xb3, 0x8c, 0x18, 0x6c, 0xc5, 0x1e, 0x34, 0xc3,
		0x0b, 0x69, 0xe3, 0xa5, 0xf5, 0x89, 0xc8, 0x6c, 0xb1, 0x5f, 0xf3, 0x39, 0x9d, 0x35, 0x23, 0xa3,
		0xe6, 0x48, 0xb0, 0x0c, 0x40, 0x83, 0x3b, 0x00, 0x34, 0xb0, 0x68, 0x5a, 0xcd, 0x47, 0xee, 0xe9,
		0x4a, 0x29, 0xe1, 0x5b, 0x39, 0x5c, 0x30, 0x9e, 0x8d, 0x22, 0x46, 0xed, 0xda, 0x86, 0x94, 0xe5,
		0x1e, 0xa4, 0x2c, 0xfe, 0x69, 0x48, 0x3b, 0x24, 0xb1, 0xe2, 0x48, 0x1c, 0xce, 0x53, 0x6e, 0x86,
		0x28, 0x2e, 0x20, 0xe5, 0x3b, 0x58, 0x0f, 0x2c, 0xf0, 0x84, 0xce, 0xe6, 0xd5, 0x0c, 0x40, 0xac,
		0xb7, 0xae, 0xf2, 0x8b, 0x16, 0xee, 0xd7, 0x6e, 0xd8, 0x3a, 0xf6, 0x06, 0x13, 0xc3, 0xaa, 0x60,
		0xf3, 0xac, 0xb4, 0xc3, 0x26, 0x2b, 0xe6, 0x38, 0xdc, 0xc9, 0xa9, 0xa8, 0x9a, 0xb3, 0x49, 0xdf,
		0xd2, 0x04, 0x7c, 0x0e, 0x47, 0x5d, 0x92, 0xf2, 0x5c, 0x5c, 0x17, 0x84, 0x84, 0xd1, 0xfc, 0xd4,
		0x18, 0xcb, 0x49, 0x30, 0x97, 0x22, 0x73, 0x3c, 0x39, 0xf8, 0x79, 0x09, 0xba, 0x6f, 0xdf, 0x89,
		0xee, 0x0d, 0x9b, 0x55, 0xe4, 0x23, 0x8c, 0x17, 0xf1, 0xb1, 0x1c, 0xe9, 0xa9, 0x90, 0xe6, 0xcc,
		0xc3, 0x1c, 0x9f, 0x38, 0x34, 0xf5, 0xbb, 0x9c, 0x02, 0xa8, 0x89, 0xc0, 0x35, 0x3e, 0x6d, 0x8d,
		0x9a, 0x38, 0x03, 0x66, 0x62, 0x27, 0xf5, 0x82, 0x65, 0x6a, 0x61, 0x7d, 0xf2, 0x09, 0xd6, 0x68,
		0x43, 0x81, 0xc4, 0x6d, 0x41, 0xe7, 0x5a, 0x0f, 0xa9, 0xe3, 0x2b, 0x36, 0xd4, 0x3f, 0x1a, 0xd9,
		0x71, 0x0e, 0x57, 0x7a, 0xb4, 0x5f, 0xe1, 0xe1, 0x50, 0x6f, 0x68, 0xb9, 0xa2, 0x23, 0xb0, 0xe0,
		0xe0, 0x72, 0x05, 0xc7, 0x76, 0x25, 0x87, 0xe6, 0x2b, 0x36, 0xbe, 0x3b, 0xce, 0xc1, 0xc7, 0x9d,
		0xf0, 0x5f, 0x8f, 0x5a, 0x48, 0xa6, 0x1e, 0x7a, 0xe5, 0x46, 0x7e, 0x55, 0x69, 0xca, 0xb5, 0x23,
		0xfd, 0xb5, 0xd2, 0xd6, 0x95, 0x00, 0x6b, 0x2e, 0x2b, 0x24, 0x58, 0xcd, 0x23, 0x35, 0x96, 0xe2,
		0x1b, 0xa7, 0x77, 0x45, 0xbf, 0xf4, 0x62, 0xa2, 0xf2, 0x1f, 0x33, 0x10, 0x61, 0xdd, 0x4d, 0x1d,
		0x44, 0x58, 0x54, 0x3f, 0x5d, 0xb3, 0xeb, 0xbb, 0x4d, 0x84, 0x2d, 0x9c, 0x43, 0x7f, 0xee, 0x36,
		0xfc, 0xd9, 0x86, 0x6d, 0x1d, 0x04, 0x12, 0x0e, 0xe7, 0xdd, 0xd2, 0x52, 0xb7, 0xd8, 0x0a, 0x00,
		0xe7, 0x10, 0xa0, 0x05, 0x94, 0x27, 0x01, 0x5a, 0x58, 0xaf, 0xfc, 0x81, 0x73, 0xd8, 0x22, 0x01,
		0xce, 0x21, 0x38, 0x87, 0xe0, 0x1c, 0x22, 0xb0, 0x74, 0x10, 0x2c, 0xc0, 0x39, 0x7c, 0xd8, 0xd5,
		0x73, 0x70, 0x0e, 0x3b, 0x0c, 0x5f, 0xe0, 0x1c, 0xc2, 0xd7, 0x83, 0x73, 0xd8, 0xa0, 0xb6, 0xe0,
		0x1c, 0x3a, 0x89, 0x81, 0xb1, 0xb4, 0xed, 0x2a, 0x0c, 0x9c, 0x43, 0x2f, 0x93, 0x06, 0xe7, 0x10,
		0x16, 0x0c, 0x0b, 0xbe, 0x77, 0x9c, 0xc3, 0xf5, 0x8d, 0xd8, 0xa3, 0x96, 0xdd, 0x8d, 0xce, 0x88,
		0x87, 0xf6, 0xc1, 0x4b, 0xd0, 0x85, 0xf9, 0x9e, 0xed, 0xdb, 0xeb, 0xc7, 0x82, 0x7d, 0x88, 0x7a,
		0x0b, 0x0a, 0xf9, 0xf7, 0xbf, 0x90, 0x0f, 0xf6, 0x61, 0xab, 0x08, 0xd8, 0x87, 0xbb, 0x89, 0x66,
		0x41, 0x90, 0x3b, 0xaf, 0xc8, 0x85, 0x23, 0xbb, 0x81, 0x31, 0x68, 0xd5, 0xfc, 0x3b, 0x79, 0x64,
		0xf7, 0x88, 0x45, 0x3c, 0xf4, 0xc0, 0xee, 0x06, 0xd9, 0x40, 0xf4, 0x4c, 0xde, 0x23, 0xc5, 0x38,
		0xac, 0x1b, 0xc0, 0x19, 0xe4, 0xdb, 0xc8, 0xb7, 0x91, 0x6f, 0x37, 0xe4, 0xdb, 0x00, 0xce, 0x34,
		0x49, 0x00, 0x38, 0x03, 0xe0, 0x0c, 0x80, 0x33, 0x08, 0x2c, 0x1d, 0x04, 0x0b, 0x00, 0x67, 0x1a,
		0xe4, 0x00, 0x9c, 0xd9, 0xaf, 0x41, 0x01, 0x70, 0x06, 0xc0, 0x19, 0xf8, 0x7a, 0xc7, 0xb5, 0x6b,
		0xd9, 0x10, 0xc0, 0x99, 0x6d, 0xf2, 0x97, 0x10, 0xdd, 0x0e, 0xd4, 0xf1, 0x50, 0x5d, 0xdf, 0x5a,
		0xe7, 0xb7, 0xd6, 0xfd, 0x70, 0x1b, 0xf0, 0xf4, 0xed, 0x00, 0xce, 0x10, 0x80, 0x33, 0xb0, 0x60,
		0x58, 0xf0, 0x5e, 0x5b, 0xf0, 0xde, 0x02, 0x67, 0xea, 0xf7, 0x34, 0x76, 0x86, 0x99, 0xf9, 0x89,
		0x45, 0x1c, 0x87, 0x75, 0xa3, 0xca, 0x82, 0xf2, 0xfd, 0x03, 0x2a, 0xdf, 0x03, 0x2e, 0xd3, 0x2a,
		0x02, 0xb8, 0x4c, 0xe7, 0x31, 0xac, 0x13, 0xa4, 0x4c, 0x5d, 0xbc, 0xda, 0x06, 0x24, 0x73, 0xc9,
		0x59, 0xdc, 0x4f, 0x55, 0x16, 0x8c, 0x45, 0x68, 0xeb, 0x20, 0x10, 0x90, 0x90, 0x77, 0x4b, 0x79,
		0xb7, 0x40, 0x25, 0x00, 0x95, 0x80, 0xb4, 0x06, 0x69, 0x0d, 0xd2, 0x9a, 0xc6, 0xb4, 0x06, 0xa8,
		0x84, 0x26, 0x09, 0xa0, 0x12, 0x80, 0x4a, 0x00, 0x2a, 0x01, 0x81, 0xa5, 0x83, 0x60, 0x01, 0x54,
		0x42, 0x83, 0x1c, 0x50, 0x09, 0xfb, 0x35, 0x28, 0x40, 0x25, 0x00, 0x95, 0x00, 0x5f, 0xef, 0xb8,
		0x76, 0x2d, 0x1b, 0x02, 0x95, 0xb0, 0x4d, 0xfe, 0x12, 0xa2, 0xdb, 0x81, 0x3a, 0x1e, 0xaa, 0xeb,
		0x5b, 0xeb, 0xfc, 0xd6, 0xba, 0x1f, 0x6e, 0x03, 0x9e, 0xbe, 0x1d, 0xa8, 0x04, 0x02, 0x2a, 0x01,
		0x16, 0x0c, 0x0b, 0xde, 0x6b, 0x0b, 0xde, 0x5b, 0x54, 0x42, 0xcb, 0xee, 0xc6, 0xce, 0xa0, 0x09,
		0xbf, 0x70, 0x16, 0xbf, 0x51, 0x19, 0xe0, 0x09, 0x28, 0xb7, 0xa0, 0x8e, 0xff, 0x90, 0xea, 0xf8,
		0x80, 0x27, 0xb4, 0x8a, 0x00, 0x9e, 0xb0, 0x9b, 0x60, 0xd6, 0x09, 0x46, 0xa1, 0x29, 0x70, 0xe1,
		0x52, 0xf1, 0x80, 0xd8, 0x03, 0xe8, 0x81, 0x63, 0xf9, 0x06, 0x97, 0x8a, 0x23, 0x77, 0xd9, 0x65,
		0xee, 0x82, 0x4b, 0xc5, 0x71, 0xa9, 0x38, 0x4c, 0xec, 0x0e, 0x2f, 0x0f, 0x70, 0xa9, 0x38, 0x2e,
		0x15, 0x87, 0xf1, 0xee, 0x51, 0x7c, 0xc4, 0xa5, 0xe2, 0x75, 0x72, 0xb8, 0x54, 0x7c, 0x9f, 0x86,
		0x04, 0x97, 0x8a, 0xdf, 0xf3, 0x4b, 0xc5, 0x2b, 0x95, 0x92, 0x6d, 0xaf, 0x15, 0x5f, 0xaf, 0x8a,
		0xe0, 0x62, 0x71, 0x5c, 0x2c, 0xde, 0xa0, 0x6f, 0x5e, 0x57, 0x8b, 0xaf, 0xe9, 0x96, 0xd3, 0xe5,
		0xe2, 0x46, 0x69, 0xde, 0x37, 0x9a, 0x8d, 0x46, 0x22, 0x72, 0xbb, 0x62, 0xbc, 0x4e, 0xc2, 0xf5,
		0xa2, 0x71, 0x35, 0x5a, 0xbf, 0x67, 0x3c, 0x16, 0x59, 0x9a, 0xb0, 0x19, 0xcd, 0x3f, 0x9f, 0x36,
		0xa5, 0xb2, 0xb8, 0x62, 0xbc, 0x41, 0xe1, 0x70, 0xc5, 0x38, 0x6a, 0xa1, 0xae, 0xb9, 0xf6, 0xdd,
		0xbe, 0x62, 0x1c, 0x07, 0x77, 0x13, 0x0e, 0xee, 0xf6, 0x56, 0xf5, 0x1b, 0x3a, 0xb8, 0x3b, 0xe5,
		0x3a, 0x53, 0x32, 0x94, 0x2e, 0xdb, 0x28, 0x1d, 0xc2, 0x95, 0x7d, 0x63, 0x3b, 0xa4, 0xe7, 0x60,
		0xc9, 0x82, 0x25, 0x0b, 0x74, 0x0d, 0xca, 0xe7, 0x40, 0xd7, 0xd4, 0x55, 0xa6, 0xc1, 0x92, 0x6d,
		0x91, 0x00, 0x4b, 0x16, 0x2c, 0x59, 0xb0, 0x64, 0x11, 0x58, 0x3a, 0x08, 0x16, 0x60, 0xc9, 0x3e,
		0xec, 0xdd, 0x1d, 0xb0, 0x64, 0x3b, 0x0c, 0x5f, 0x60, 0xc9, 0xc2, 0xd7, 0x83, 0x25, 0xdb, 0xa0,
		0xb6, 0x60, 0xc9, 0x3a, 0x89, 0x81, 0x63, 0xb7, 0xed, 0x2a, 0x0c, 0x2c, 0x59, 0x2f, 0x93, 0x06,
		0x4b, 0x16, 0x16, 0x0c, 0x0b, 0xbe, 0x6f, 0x2c, 0xd9, 0x1a, 0x68, 0xc0, 0x51, 0xd3, 0xd6, 0x46,
		0x57, 0x44, 0xd9, 0xfc, 0xd9, 0xef, 0x8b, 0x47, 0x2f, 0xc1, 0x6b, 0x8a, 0x3d, 0x10, 0x70, 0x65,
		0x51, 0x74, 0x41, 0x35, 0xff, 0x01, 0x55, 0xf3, 0xc1, 0x95, 0x6d, 0x15, 0x01, 0x57, 0x76, 0x67,
		0x21, 0x2d, 0x04, 0x18, 0xea, 0x1b, 0xbe, 0xc0, 0x98, 0x0d, 0x88, 0x40, 0x80, 0x21, 0x38, 0x96,
		0x72, 0xc0, 0x98, 0x45, 0x06, 0xb3, 0xcb, 0x0c, 0x06, 0x8c, 0x59, 0x30, 0x66, 0x61, 0x62, 0x77,
		0x78, 0x91, 0x00, 0xc6, 0x2c, 0x18, 0xb3, 0x30, 0xde, 0x3d, 0x8a, 0x8f, 0x60, 0xcc, 0xd6, 0xc9,
		0x81, 0x31, 0xbb, 0x4f, 0x43, 0x02, 0xc6, 0xec, 0xfd, 0x66, 0xcc, 0xd6, 0xd5, 0x4b, 0xb6, 0xe4,
		0xcd, 0x6e, 0x2e, 0x8f, 0x80, 0x3c, 0x0b, 0xf2, 0x6c, 0xab, 0xea, 0xf9, 0x50, 0x68, 0x37, 0xaa,
		0x59, 0x2d, 0x8f, 0xf6, 0xd1, 0xd2, 0xfb, 0xd7, 0xbd, 0x77, 0x4f, 0x64, 0x3f, 0xb1, 0xcf, 0xfc,
		0xad, 0x52, 0xd5, 0xf1, 0x5e, 0xff, 0x96, 0xde, 0x0a, 0x31, 0x77, 0xf9, 0x0d, 0x9f, 0x17, 0x7b,
		0x3a, 0xc5, 0x03, 0x1f, 0x7d, 0xff, 0x0f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff,
		0xff, 0x2a, 0xfb, 0x78, 0x99, 0xcf, 0x90, 0x01, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes(){
  ΛEnumTypes = map[string][]reflect.Type{
	"/retail-area/location/coordinate-system": []reflect.Type{
		reflect.TypeOf((E_IntelSraSource_RetailArea_Location_CoordinateSystem)(0)),
	},
	"/retail-area/source/location/coordinate-system": []reflect.Type{
		reflect.TypeOf((E_IntelSraSource_RetailArea_Location_CoordinateSystem)(0)),
	},
	"/retail-area/source/video/source-type": []reflect.Type{
		reflect.TypeOf((E_IntelSraSource_RetailArea_Source_Video_SourceType)(0)),
	},
	"/shelf-monitoring/object-detection-application/device": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device)(0)),
	},
	"/shelf-monitoring/object-detection-application/precision": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision)(0)),
	},
	"/shopper-monitoring/emotion-recognition-application/device": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device)(0)),
	},
	"/shopper-monitoring/emotion-recognition-application/precision": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision)(0)),
	},
	"/shopper-monitoring/face-detection-application/device": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device)(0)),
	},
	"/shopper-monitoring/face-detection-application/precision": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision)(0)),
	},
	"/shopper-monitoring/head-pose-detection-application/device": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device)(0)),
	},
	"/shopper-monitoring/head-pose-detection-application/precision": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision)(0)),
	},
	"/store-traffic-monitoring/person-detection-application/device": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Device)(0)),
	},
	"/store-traffic-monitoring/person-detection-application/precision": []reflect.Type{
		reflect.TypeOf((E_IntelSra_ShelfMonitoring_ObjectDetectionApplication_Precision)(0)),
	},
  }
}

